1. Fixed a typo when generating hash 2. During the fixing process I got errors such as: --- Object of type 'Response' is not JSON serializable --- AttributeError: 'UserModel' object has no attribute '_UserModel__generarte_hash' --- NoneType has no attribute get flask get_user_by_email 3. Fixed them by adding a missing static method, setting the Content-Type to 'application/json', uninstalling jwt and PyJWT modules and then installed PyJWT only to being able to use encode function properly. TOLEARN: use more debugging cookies provided by PyCharm :)